change imports to be ready for ha 2024.06
V4n1X/ha_hisense_tv pull request #6
Opened 2024-12-16 21:31 UTC by sven-probst

change imports to be ready for ha 2024.06

loads without any warning

2024-12-16 21:31 UTC, sven-probst commented
sorry, ready for 2025.06

2024-12-23 13:02 UTC, callifo commented
Thanks for the update, working great for me and cleared up a bunch of startup errors.

2025-04-13 15:25 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +            media_content_type=MediaClass.APPS,
think this should be media_content_type=MediaClass.APP not APPS?

2025-04-13 15:26 UTC, spycle requested changes

2025-04-13 15:26 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +                media_content_type=MediaClass.APPS,
think this should be media_content_type=MediaClass.APP not APPS?

2025-04-13 19:31 UTC, sven-probst commented on custom_components/hisense_tv/media_player.py
> +            media_content_type=MediaClass.APPS,
I think it should be MediaType.APPS, see the new patch.

2025-04-13 21:08 UTC, spycle requested changes
MediaBrowser still doesn't work for me after these changes, but then it hasn't for a while. Maybe it does for you?

2025-04-13 21:08 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +                                media_content_type=MediaType.APP,
ok cool, so should this one not be MediaType.APPS then?

2025-04-13 21:08 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +                                media_class=MediaType.CHANNEL,
`media_class=MediaClass.CHANNEL` ?

2025-04-13 21:08 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +        elif media_type == MediaClass.APP:
`elif media_type == MediaType.APPS:` ?

2025-04-13 21:08 UTC, spycle commented on custom_components/hisense_tv/media_player.py
> +        elif media_type == MediaClass.APP:
and line 703 above `if media_type == MediaType.CHANNEL:` ?

2025-04-18 12:20 UTC, sven-probst commented
@spycle could you please check the last commit. The media player now lists the installed apps. To play other local media such as pictures or videos, you should use DLNA, as the vidaa app does.

2025-04-20 11:37 UTC, spycle commented
@sven-probst not quite working. I have channels back and that works, applications not there yet.

```
File "/config/custom_components/hisense_tv/media_player.py", line 710, in async_browse_media
    return await self._build_app_list_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hisense_tv/media_player.py", line 671, in _build_app_list_node
    payload_string = msg[0].payload
                     ~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

There's still a couple of MediaType.APP that maybe should be MediaType.APPS but changing that didn't help unfortunately. It's MediaClass.APP and MediaType.APPS right? Confusing

2025-04-20 12:29 UTC, spycle commented
fyi 
![image](https://github.com/user-attachments/assets/00ed5fc3-ee4a-44be-8621-34492cee273f)

2025-04-20 14:59 UTC, sven-probst commented
could you please have a look at the topic the app uses to get the applist? (your tool does not show that, please subscribe  `-t "hisense/#"` with mosquitto_sub.) And it could be useful to have the full answer to a published topic `/remoteapp/tv/ui_service/xx:xx:xx:xx:xx:xx$vidaa_common/actions/capability` . If possible it would help to have a full log of topic 'hisense/#' with mosquitto_sub while starting and navigating the vidaa app. Just to give you an impression what the actual code does with my TV:
![image](https://github.com/user-attachments/assets/672ff2d5-a0a7-4bf5-99cb-80f3167e4973)

2025-04-21 15:14 UTC, sven-probst commented
@spycle I think the problem is a different transport protocol offered by the TV. Do you also get a channellist displayed? I never saw a channel list in the mqtt conversation with my vidaa TV.

2025-04-21 17:16 UTC, spycle commented
> @spycle I think the problem is a different transport protocol offered by the TV. Do you also get a channellist displayed? I never saw a channel list in the mqtt conversation with my vidaa TV.

You mean this?
![image](https://github.com/user-attachments/assets/322fe940-0a5b-47ef-996b-21abc7cc135b)
![image](https://github.com/user-attachments/assets/8e68576d-a953-42fe-bfcf-67e2a9624562)

that works now

With Applications it's still exactly the same error.

2025-04-21 17:18 UTC, spycle commented
> could you please have a look at the topic the app uses to get the applist? (your tool does not show that, please subscribe `-t "hisense/#"` with mosquitto_sub.) And it could be useful to have the full answer to a published topic `/remoteapp/tv/ui_service/xx:xx:xx:xx:xx:xx$vidaa_common/actions/capability` . If possible it would help to have a full log of topic 'hisense/#' with mosquitto_sub while starting and navigating the vidaa app. 

I'll see what I can do. Cheers

2025-04-21 17:45 UTC, spycle commented
OK in MQTT Explorer, if I publish hisense/remoteapp/tv/ui_service/HomeAssistant/actions/applist then the below generates;

![image](https://github.com/user-attachments/assets/8ea73747-d320-457c-9933-95a557f3caed)

Promising

When I publish hisense/remoteapp/tv/ui_service/XX:XX:XX:XX:XX:XX$vidaa_common/actions/capability I get {}. The below is from XX:XX:XX:XX:XX:XX$normal however;

{
  "pvr": 1,
  "reminder": 1,
  "boardVersion": "MSD6886",
  "produceDate": "P0219",
  "uniqueDeviceId": "8610030090000060000006414e53da145c3a79b5a33306ce1fffb043",
  "softwareVersion": "V0000.01.00C.P0219",
  "vendorBrand": "his",
  "searchnow": 1,
  "emanual": 1,
  "chipplatform": "mstar6886",
  "deviceType": 0,
  "playerFamilyVersion": "002000000",
  "playerFamilyName": "VD6886V_EU",
  "devicemsg": "HE55A6900FUWTS",
  "zone": 0,
  "launcherVersion": "os_t.launcher.1.0.4.0.L011500",
  "vidaaappVersion": "os_t.vidaaapp.1.0.1.0.K042600",
  "sportappVersion": "os_t.sportapp.1.0.0.0.J100100"
}

2025-04-21 18:46 UTC, sven-probst commented
@spycle have you also tested this with https://github.com/V4n1X/ha_hisense_tv/pull/6/commits/a1ee7fcc9aa6259e0f2cb2c9595a4b0e5e62c377 included? (there was a bug in the theme before). Nonetheless, the latest patch is more relaxed when trying to get the thumbnails.

2025-04-21 21:47 UTC, spycle commented
Yeah I've got https://github.com/V4n1X/ha_hisense_tv/commit/a1ee7fcc9aa6259e0f2cb2c9595a4b0e5e62c377, your branch must have it. Still the same error unfortunately

```
  File "/config/custom_components/hisense_tv/media_player.py", line 762, in async_browse_media
    return await self._build_app_list_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hisense_tv/media_player.py", line 673, in _build_app_list_node
    payload_string = msg[0].payload
                     ~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

Don't know if relevant but I turned on debug and also have

```
Timeout: keine Nachricht innerhalb von 10 Sekunden auf Topic 'hisense/remoteapp/mobile/HomeAssistant/platform_service/data/getdeviceinfo'
```

Appreciate you looking at this by the way

2025-04-21 22:27 UTC, spycle commented
OK messing around a bit. I'm not sure I have getdeviceinfo but I do have gettvinfo. Changing that in the code seemed to get rid of the above warning and now I get

This error originated from a custom integration.

```
Timeout: keine Nachricht innerhalb von 10 Sekunden auf Topic 'hisense/remoteapp/mobile/HomeAssistant/ui_service/data/applist'
```

2025-04-22 18:39 UTC, sven-probst commented
@spycle I'm not sure if this is just a timing-problem of the actual code: could you please change `await asyncio.sleep(0.5)` in helper.py to `await asyncio.sleep(2)`. (maybe your mqtt-broker is very busy?) a "mosquito_sub-log" of the communication of the app with the TV would be optimal.

2025-04-22 19:09 UTC, spycle commented
OK I've got it working. Couldn't figure out what my transport_protocol was but that was the first issue so changed this;

```
#  get getdeviceinfo
        stream_deviceinfo, unsubscribe_deviceinfo = await mqtt_pub_sub(
            hass=self._hass,
            #pub=self._out_topic("/remoteapp/tv/platform_service/%s/actions/getdeviceinfo"),
            #sub=self._in_topic("/remoteapp/mobile/%s/platform_service/data/getdeviceinfo"),
            pub=self._out_topic("/remoteapp/tv/platform_service/%s/actions/gettvinfo"),
            sub=self._in_topic("/remoteapp/mobile/%s/platform_service/data/gettvinfo"),
        )
```

then forced this;

```
        # dynamic topic based on available transport_protocol
        _LOGGER.debug("Transport protocol: %s", transport_protocol)
        vidaaapplist_topic = (
            #"/remoteapp/tv/ui_service/%s/actions/vidaaapplist"
            #if transport_protocol != "1140"
            #else "/remoteapp/tv/ui_service/%s/actions/applist"
            "/remoteapp/tv/ui_service/%s/actions/applist"
        )
```
I don't seem to have icons..

```
  {
    "url": "url376",
    "isunInstalled": false,
    "name": "Amazon Music",
    "from": "",
    "storeType": 99,
    "appId": "376"
  },
```
so forced this;

```
for nid, item in self._app_list.items():
                        _LOGGER.debug("adding app %s", item.get("name"))
                        #match = re.search(r'https?://[^\s]+', item.get("httpIcon"))
                        #thumbnail = match.group(0) if match else None
                        thumbnail = None
```

Not sure how to get a mosquito_sub-log but I'll see what I can do...

2025-04-22 19:23 UTC, spycle commented
unless this is most of it;

![image](https://github.com/user-attachments/assets/54a925b2-e5ef-4be9-b8a8-ceb62dc94ba1)

2025-04-24 18:15 UTC, sven-probst commented
@spycle could you please check if the new code is correct for your TV?

2025-04-24 18:59 UTC, spycle commented
Nice work. Media Browser now works perfectly.

Found a typo in the mute action though
![image](https://github.com/user-attachments/assets/ab65c92a-d151-4829-a1a6-c1fb7922e952)

2025-04-24 19:12 UTC, sven-probst commented
@spycle that typo is maybe in a self defined action in your configuration?!

2025-04-24 20:26 UTC, spycle commented
Oh crap yeah, ignore me. That's Universal Media Player

2026-04-11 15:06 UTC, merged